name: Check CLA

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-no-cla:
    if: !contains(github.event.pull_request.labels.*.name, 'cla')
    runs-on: ubuntu-latest
    steps:
      - name: Fail for missing cla label
        run: |
          echo "cla label missing. See CONTRIBUTING.md."
          exit 1
